package gg.warcraft.monolith.api;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        Character tes;
        String tes22;
        var test = "lmao";
        return true;
    }
}
