package gg.warcraft.monolith.api.item;

/**
 * ItemType serves as an abstraction layer between Monolith plugin code and the eventual server implementation the
 * plugin is run on. It is identical to part of Spigot's {@code Material} and the server adapter will substitute its
 * values with the correct implementation during runtime.
 */
public enum ItemType {
    AIR("minecraft:air", 0),
    STONE("minecraft:stone", 1),
    GRANITE("minecraft:stone", 1, 1),
    POLISHED_GRANITE("minecraft:stone", 1, 2),
    DIORITE("minecraft:stone", 1, 3),
    POLISHED_DIORITE("minecraft:stone", 1, 4),
    ANDESITE("minecraft:stone", 1, 5),
    POLISHED_ANDESITE("minecraft:stone", 1, 6),
    GRASS("minecraft:grass", 2),
    DIRT("minecraft:dirt", 3),
    COARSE_DIRT("minecraft:dirt", 3, 1),
    PODZOL("minecraft:dirt", 3, 2),
    COBBLESTONE("minecraft:dirt", 4),
    OAK_WOOD_PLANK("minecraft:planks", 5),
    SPRUCE_WOOD_PLANK("minecraft:planks", 5, 1),
    BIRCH_WOOD_PLANK("minecraft:planks", 5, 2),
    JUNGLE_WOOD_PLANK("minecraft:planks", 5, 3),
    ACACIA_WOOD_PLANK("minecraft:planks", 5, 4),
    DARK_OAK_WOOD_PLANK("minecraft:planks", 5, 5),
    OAK_SAPLING("minecraft:sapling", 6),
    SPRUCE_SAPLING("minecraft:sapling", 6, 1),
    BIRCH_SAPLING("minecraft:sapling", 6, 2),
    JUNGLE_SAPLING("minecraft:sapling", 6, 3),
    ACACIA_SAPLING("minecraft:sapling", 6, 4),
    DARK_OAK_SAPLING("minecraft:sapling", 6, 5),
    BEDROCK("minecraft:bedrock", 7),
    FLOWING_WATER("minecraft:flowing_water", 8),
    STILL_WATER("minecraft:water", 9),
    FLOWING_LAVA("minecraft:flowing_lava", 10),
    STILL_LAVA("minecraft:lava", 11),
    SAND("minecraft:sand", 12),
    RED_SAND("minecraft:sand", 12, 1),
    GRAVEL("minecraft:gravel", 13),
    GOLD_ORE("minecraft:gold_ore", 14),
    IRON_ORE("minecraft:iron_ore", 15),
    COAL_ORE("minecraft:coal_ore", 16),
    OAK_WOOD("minecraft:log", 17),
    SPRUCE_WOOD("minecraft:log", 17, 1),
    BIRCH_WOOD("minecraft:log", 17, 2),
    JUNGLE_WOOD("minecraft:log", 17, 3),
    OAK_LEAVES("minecraft:leaves", 18),
    SPRUCE_LEAVES("minecraft:leaves", 18, 1),
    BIRCH_LEAVES("minecraft:leaves", 18, 2),
    JUNGLE_LEAVES("minecraft:leaves", 18, 3),
    SPONGE("minecraft:sponge", 19),
    WET_SPONGE("minecraft:sponge", 19, 1),
    GLASS("minecraft:glass", 20),
    LAPIS_LAZULI_ORE("minecraft:lapis_ore", 21),
    LAPIS_LAZULI_BLOCK("minecraft:lapis_block", 22),
    DISPENSER("minecraft:dispenser", 23),
    SANDSTONE("minecraft:sandstone", 24),
    CHISELED_SANDSTONE("minecraft:sandstone", 24, 1),
    SMOOTH_SANDSTONE("minecraft:sandstone", 24, 2),
    NOTE_BLOCK("minecraft:noteblock", 25),
    POWERED_RAIL("minecraft:golden_rail", 27),
    DETECTOR_RAIL("minecraft:detector_rail", 28),
    STICKY_PISTON("minecraft:sticky_piston", 29),
    COBWEB("minecraft:web", 30),
    DEAD_SHRUB("minecraft:tallgrass", 31),
    TALL_GRASS("minecraft:tallgrass", 31, 1),
    FERN("minecraft:tallgrass", 31, 2),
    DEAD_BUSH("minecraft:deadbush", 32),
    PISTON("minecraft:piston", 33),
    PISTON_HEAD("minecraft:piston_head", 34),
    WHITE_WOOL("minecraft:wool", 35),
    ORANGE_WOOL("minecraft:wool", 35, 1),
    MAGENTA_WOOL("minecraft:wool", 35, 2),
    LIGHT_BLUE_WOOL("minecraft:wool", 35, 3),
    YELLOW_WOOL("minecraft:wool", 35, 4),
    LIME_WOOL("minecraft:wool", 35, 5),
    PINK_WOOL("minecraft:wool", 35, 6),
    GRAY_WOOL("minecraft:wool", 35, 7),
    LIGHT_GRAY_WOOL("minecraft:wool", 35, 8),
    CYAN_WOOL("minecraft:wool", 35, 9),
    PURPLE_WOOL("minecraft:wool", 35, 10),
    BLUE_WOOL("minecraft:wool", 35, 11),
    BROWN_WOOL("minecraft:wool", 35, 12),
    GREEN_WOOL("minecraft:wool", 35, 13),
    RED_WOOL("minecraft:wool", 35, 14),
    BLACK_WOOL("minecraft:wool", 35, 15),
    DANDELION("minecraft:yellow_flower", 37),
    POPPY("minecraft:red_flower", 38),
    BLUE_ORCHID("minecraft:red_flower", 38, 1),
    ALLIUM("minecraft:red_flower", 38, 2),
    AZURE_BLUET("minecraft:red_flower", 38, 3),
    RED_TULIP("minecraft:red_flower", 38, 4),
    ORANGE_TULIP("minecraft:red_flower", 38, 5),
    WHITE_TULIP("minecraft:red_flower", 38, 6),
    PINK_TULIP("minecraft:red_flower", 38, 7),
    OXEYE_DAISY("minecraft:red_flower", 38, 8),
    BROWN_MUSHROOM("minecraft:brown_mushroom", 39),
    RED_MUSHROOM("minecraft:red_mushroom", 40),
    GOLD_BLOCK("minecraft:gold_block", 41),
    IRON_BLOCK("minecraft:iron_block", 42),
    DOUBLE_STONE_SLAB("minecraft:double_stone_slab", 43),
    DOUBLE_SANDSTONE_SLAB("minecraft:double_stone_slab", 43, 1),
    DOUBLE_WOOD_SLAB("minecraft:double_stone_slab", 43, 2),
    DOUBLE_COBBLESTONE_SLAB("minecraft:double_stone_slab", 43, 3),
    DOUBLE_BRICK_SLAB("minecraft:double_stone_slab", 43, 4),
    DOUBLE_STONE_BRICK_SLAB("minecraft:double_stone_slab", 43, 5),
    DOUBLE_NETHER_BRICK_SLAB("minecraft:double_stone_slab", 43, 6),
    DOUBLE_QUARTZ_SLAB("minecraft:double_stone_slab", 43, 7),
    STONE_SLAB("minecraft:stone_slab", 44),
    SANDSTONE_SLAB("minecraft:stone_slab", 44, 1),
    WOOD_SLAB("minecraft:stone_slab", 44, 2),
    COBBLESTONE_SLAB("minecraft:stone_slab", 44, 3),
    BRICK_SLAB("minecraft:stone_slab", 44, 4),
    STONE_BRICK_SLAB("minecraft:stone_slab", 44, 5),
    NETHER_BRICK_SLAB("minecraft:stone_slab", 44, 6),
    QUARTZ_SLAB("minecraft:stone_slab", 44, 7),
    BRICKS("minecraft:brick_block", 45),
    TNT("minecraft:tnt", 46),
    BOOKSHELF("minecraft:bookshelf", 47),
    MOSS_STONE("minecraft:mossy_cobblestone", 48),
    OBSIDIAN("minecraft:obsidian", 49),
    TORCH("minecraft:torch", 50),
    FIRE("minecraft:fire", 51),
    MONSTER_SPAWNER("minecraft:mob_spawner", 52),
    OAK_WOOD_STAIRS("minecraft:oak_stairs", 53),
    CHEST("minecraft:chest", 54),
    REDSTONE_WIRE("minecraft:redstone_wire", 55),
    DIAMOND_ORE("minecraft:diamond_ore", 56),
    DIAMOND_BLOCK("minecraft:diamond_block", 57),
    CRAFTING_TABLE("minecraft:crafting_table", 58),
    WHEAT_CROPS("minecraft:wheat", 59),
    FARMLAND("minecraft:farmland", 60),
    FURNACE("minecraft:furnace", 61),
    BURNING_FURNACE("minecraft:lit_furnace", 62),
    STANDING_SIGN_BLOCK("minecraft:standing_sign", 63),
    OAK_DOOR_BLOCK("minecraft:wooden_door", 64),
    LADDER("minecraft:ladder", 65),
    RAIL("minecraft:rail", 66),
    COBBLESTONE_STAIRS("minecraft:stone_stairs", 67),
    WALL_MOUNTED_SIGN_BLOCK("minecraft:wall_sign", 68),
    LEVER("minecraft:lever", 69),
    STONE_PRESSURE_PLATE("minecraft:stone_pressure_plate", 70),
    IRON_DOOR_BLOCK("minecraft:iron_door", 71),
    WOOD_PRESSURE_PLATE("minecraft:wooden_pressure_plate", 72),
    REDSTONE_ORE("minecraft:redstone_ore", 73),
    GLOWING_REDSTONE_ORE("minecraft:lit_redstone_ore", 74),
    REDSTONE_TORCH_OFF("minecraft:unlit_redstone_torch", 75),
    REDSTONE_TORCH_ON("minecraft:redstone_torch", 76),
    STONE_BUTTON("minecraft:stone_button", 77),
    SNOW("minecraft:snow_layer", 78),
    ICE("minecraft:ice", 79),
    SNOW_BLOCK("minecraft:snow", 80),
    CACTUS("minecraft:cactus", 81),
    CLAY("minecraft:clay", 82),
    JUKEBOX("minecraft:jukebox", 84),
    OAK_FENCE("minecraft:fence", 85),
    PUMPKIN("minecraft:pumpkin", 86),
    NETHERRACK("minecraft:netherrack", 87),
    SOUL_SAND("minecraft:soul_sand", 88),
    GLOWSTONE("minecraft:glowstone", 89),
    NETHER_PORTAL("minecraft:portal", 90),
    JACK_OLANTERN("minecraft:lit_pumpkin", 91),
    CAKE_BLOCK("minecraft:cake", 92),
    REDSTONE_REPEATER_BLOCK_OFF("minecraft:unpowered_repeater", 93),
    REDSTONE_REPEATER_BLOCK_ON("minecraft:powered_repeater", 94),
    WHITE_STAINED_GLASS("minecraft:stained_glass", 95),
    ORANGE_STAINED_GLASS("minecraft:stained_glass", 95, 1),
    MAGENTA_STAINED_GLASS("minecraft:stained_glass", 95, 2),
    LIGHT_BLUE_STAINED_GLASS("minecraft:stained_glass", 95, 3),
    YELLOW_STAINED_GLASS("minecraft:stained_glass", 95, 4),
    LIME_STAINED_GLASS("minecraft:stained_glass", 95, 5),
    PINK_STAINED_GLASS("minecraft:stained_glass", 95, 6),
    GRAY_STAINED_GLASS("minecraft:stained_glass", 95, 7),
    LIGHT_GRAY_STAINED_GLASS("minecraft:stained_glass", 95, 8),
    CYAN_STAINED_GLASS("minecraft:stained_glass", 95, 9),
    PURPLE_STAINED_GLASS("minecraft:stained_glass", 95, 10),
    BLUE_STAINED_GLASS("minecraft:stained_glass", 95, 11),
    BROWN_STAINED_GLASS("minecraft:stained_glass", 95, 12),
    GREEN_STAINED_GLASS("minecraft:stained_glass", 95, 13),
    RED_STAINED_GLASS("minecraft:stained_glass", 95, 14),
    BLACK_STAINED_GLASS("minecraft:stained_glass", 95, 15),
    WOOD_TRAPDOOR("minecraft:trapdoor", 96),
    STONE_MONSTER_EGG("minecraft:monster_egg", 97),
    COBBLESTONE_MONSTER_EGG("minecraft:monster_egg", 97, 1),
    STONE_BRICK_MONSTER_EGG("minecraft:monster_egg", 97, 2),
    MOSSY_STONE_BRICK_MONSTER_EGG("minecraft:monster_egg", 97, 3),
    CRACKED_STONE_BRICK_MONSTER_EGG("minecraft:monster_egg", 97, 5),
    CHISELED_STONE_BRICK_MONSTER_EGG("minecraft:monster_egg", 97, 5),
    STONE_BRICKS("minecraft:stonebrick", 98),
    MOSSY_STONE_BRICKS("minecraft:stonebrick", 98, 1),
    CRACKED_STONE_BRICKS("minecraft:stonebrick", 98, 2),
    CHISELED_STONE_BRICKS("minecraft:stonebrick", 98, 3),
    BROWN_MUSHROOM_BLOCK("minecraft:brown_mushroom_block", 99),
    RED_MUSHROOM_BLOCK("minecraft:red_mushroom_block", 100),
    IRON_BARS("minecraft:iron_bars", 101),
    GLASS_PANE("minecraft:glass_pane", 102),
    MELON_BLOCK("minecraft:melon_block", 103),
    PUMPKIN_STEM("minecraft:pumpkin_stem", 104),
    MELON_STEM("minecraft:melon_stem", 105),
    VINES("minecraft:vine", 106),
    OAK_FENCE_GATE("minecraft:fence_gate", 107),
    BRICK_STAIRS("minecraft:brick_stairs", 108),
    STONE_BRICK_STAIRS("minecraft:stone_brick_stairs", 109),
    MYCELIUM("minecraft:mycelium", 110),
    LILY_PAD("minecraft:waterlily", 111),
    NETHER_BRICK_BLOCK("minecraft:nether_brick", 112),
    NETHER_BRICK_FENCE("minecraft:nether_brick_fence", 113),
    NETHER_BRICK_STAIRS("minecraft:nether_brick_stairs", 114),
    ENCHANTMENT_TABLE("minecraft:enchanting_table", 116),
    END_PORTAL("minecraft:end_portal", 119),
    END_PORTAL_FRAME("minecraft:end_portal_frame", 120),
    END_STONE("minecraft:end_stone", 121),
    DRAGON_EGG("minecraft:dragon_egg", 122),
    REDSTONE_LAMP_INACTIVE("minecraft:redstone_lamp", 123),
    REDSTONE_LAMP_ACTIVE("minecraft:lit_redstone_lamp", 124),
    DOUBLE_OAK_WOOD_SLAB("minecraft:double_wooden_slab", 125),
    DOUBLE_SPRUCE_WOOD_SLAB("minecraft:double_wooden_slab", 125, 1),
    DOUBLE_BIRCH_WOOD_SLAB("minecraft:double_wooden_slab", 125, 2),
    DOUBLE_JUNGLE_WOOD_SLAB("minecraft:double_wooden_slab", 125, 3),
    DOUBLE_ACACIA_WOOD_SLAB("minecraft:double_wooden_slab", 125, 4),
    DOUBLE_DARK_OAK_WOOD_SLAB("minecraft:double_wooden_slab", 125, 5),
    OAK_WOOD_SLAB("minecraft:wooden_slab", 126),
    SPRUCE_WOOD_SLAB("minecraft:wooden_slab", 126, 1),
    BIRCH_WOOD_SLAB("minecraft:wooden_slab", 126, 2),
    JUNGLE_WOOD_SLAB("minecraft:wooden_slab", 126, 3),
    ACACIA_WOOD_SLAB("minecraft:wooden_slab", 126, 4),
    DARK_OAK_WOOD_SLAB("minecraft:wooden_slab", 126, 5),
    COCOA("minecraft:cocoa", 127),
    SANDSTONE_STAIRS("minecraft:sandstone_stairs", 128),
    EMERALD_ORE("minecraft:emerald_ore", 129),
    ENDER_CHEST("minecraft:ender_chest", 130),
    TRIPWIRE_HOOK("minecraft:tripwire_hook", 131),
    TRIPWIRE("minecraft:tripwire_hook", 132),
    EMERALD_BLOCK("minecraft:emerald_block", 133),
    SPRUCE_WOOD_STAIRS("minecraft:spruce_stairs", 134),
    BIRCH_WOOD_STAIRS("minecraft:birch_stairs", 135),
    JUNGLE_WOOD_STAIRS("minecraft:jungle_stairs", 136),
    COMMAND_BLOCK("minecraft:command_block", 137),
    BEACON("minecraft:beacon", 138),
    COBBLESTONE_WALL("minecraft:cobblestone_wall", 139),
    MOSSY_COBBLESTONE_WALL("minecraft:cobblestone_wall", 139, 1),
    CARROTS("minecraft:carrots", 141),
    POTATOES("minecraft:potatoes", 142),
    WOOD_BUTTON("minecraft:wooden_button", 143),
    MOB_HEAD("minecraft:skull", 144),
    ANVIL("minecraft:anvil", 145),
    TRAPPED_CHEST("minecraft:trapped_chest", 146),
    WEIGHTED_PRESSURE_PLATE_LIGHT("minecraft:light_weighted_pressure_plate", 147),
    WEIGHTED_PRESSURE_PLATE_HEAVY("minecraft:heavy_weighted_pressure_plate", 148),
    REDSTONE_COMPARATOR_INACTIVE("minecraft:unpowered_comparator", 149),
    REDSTONE_COMPARATOR_ACTIVE("minecraft:powered_comparator", 150),
    DAYLIGHT_SENSOR("minecraft:daylight_detector", 151),
    REDSTONE_BLOCK("minecraft:redstone_block", 152),
    NETHER_QUARTZ_ORE("minecraft:quartz_ore", 153),
    HOPPER("minecraft:hopper", 154),
    QUARTZ_BLOCK("minecraft:quartz_block", 155),
    CHISELED_QUARTZ_BLOCK("minecraft:quartz_block", 155, 1),
    PILLAR_QUARTZ_BLOCK("minecraft:quartz_block", 155, 2),
    QUARTZ_STAIRS("minecraft:quartz_stairs", 156),
    ACTIVATOR_RAIL("minecraft:activator_rail", 157),
    DROPPER("minecraft:dropper", 158),
    WHITE_HARDENED_CLAY("minecraft:stained_hardened_clay", 159),
    ORANGE_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 1),
    MAGENTA_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 2),
    LIGHT_BLUE_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 3),
    YELLOW_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 4),
    LIME_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 5),
    PINK_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 6),
    GRAY_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 7),
    LIGHT_GRAY_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 8),
    CYAN_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 9),
    PURPLE_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 10),
    BLUE_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 11),
    BROWN_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 12),
    GREEN_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 13),
    RED_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 14),
    BLACK_HARDENED_CLAY("minecraft:stained_hardened_clay", 159, 15),
    WHITE_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160),
    ORANGE_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 1),
    MAGENTA_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 2),
    LIGHT_BLUE_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 3),
    YELLOW_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 4),
    LIME_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 5),
    PINK_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 6),
    GRAY_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 7),
    LIGHT_GRAY_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 8),
    CYAN_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 9),
    PURPLE_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 10),
    BLUE_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 11),
    BROWN_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 12),
    GREEN_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 13),
    RED_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 14),
    BLACK_STAINED_GLASS_PANE("minecraft:stained_glass_pane", 160, 15),
    ACACIA_LEAVES("minecraft:leaves2", 161),
    DARK_OAK_LEAVES("minecraft:leaves2", 161, 1),
    ACACIA_WOOD("minecraft:log2", 162),
    DARK_OAK_WOOD("minecraft:log2", 162, 1),
    ACACIA_WOOD_STAIRS("minecraft:acacia_stairs", 163),
    DARK_OAK_WOOD_STAIRS("minecraft:dark_oak_stairs", 164),
    SLIME_BLOCK("minecraft:slime", 165),
    BARRIER("minecraft:barrier", 166),
    IRON_TRAPDOOR("minecraft:iron_trapdoor", 167),
    PRISMARINE("minecraft:prismarine", 168),
    PRISMARINE_BRICKS("minecraft:prismarine", 168, 1),
    DARK_PRISMARINE("minecraft:prismarine", 168, 2),
    SEA_LANTERN("minecraft:sea_lantern", 169),
    HAY_BALE("minecraft:hay_block", 170),
    WHITE_CARPET("minecraft:carpet", 171),
    ORANGE_CARPET("minecraft:carpet", 171, 1),
    MAGENTA_CARPET("minecraft:carpet", 171, 2),
    LIGHT_BLUE_CARPET("minecraft:carpet", 171, 3),
    YELLOW_CARPET("minecraft:carpet", 171, 4),
    LIME_CARPET("minecraft:carpet", 171, 5),
    PINK_CARPET("minecraft:carpet", 171, 6),
    GRAY_CARPET("minecraft:carpet", 171, 7),
    LIGHT_GRAY_CARPET("minecraft:carpet", 171, 8),
    CYAN_CARPET("minecraft:carpet", 171, 9),
    PURPLE_CARPET("minecraft:carpet", 171, 10),
    BLUE_CARPET("minecraft:carpet", 171, 11),
    BROWN_CARPET("minecraft:carpet", 171, 12),
    GREEN_CARPET("minecraft:carpet", 171, 13),
    RED_CARPET("minecraft:carpet", 171, 14),
    BLACK_CARPET("minecraft:carpet", 171, 15),
    HARDENED_CLAY("minecraft:hardened_clay", 172),
    BLOCK_OF_COAL("minecraft:coal_block", 173),
    PACKED_ICE("minecraft:packed_ice", 174),
    SUNFLOWER("minecraft:double_plant", 175),
    LILAC("minecraft:double_plant", 175, 1),
    DOUBLE_TALLGRASS("minecraft:double_plant", 175, 2),
    LARGE_FERN("minecraft:double_plant", 175, 3),
    ROSE_BUSH("minecraft:double_plant", 175, 4),
    PEONY("minecraft:double_plant", 175, 5),
    FREE_STANDING_BANNER("minecraft:standing_banner", 176),
    WALL_MOUNTED_BANNER("minecraft:wall_banner", 177),
    INVERTED_DAYLIGHT_SENSOR("minecraft:daylight_detector_inverted", 178),
    RED_SANDSTONE("minecraft:red_sandstone", 179),
    CHISELED_RED_SANDSTONE("minecraft:red_sandstone", 179, 1),
    SMOOTH_RED_SANDSTONE("minecraft:red_sandstone", 179, 2),
    RED_SANDSTONE_STAIRS("minecraft:red_sandstone_stairs", 180),
    DOUBLE_RED_SANDSTONE_SLAB("minecraft:double_stone_slab2", 181),
    RED_SANDSTONE_SLAB("minecraft:stone_slab2", 182),
    SPRUCE_FENCE_GATE("minecraft:spruce_fence_gate", 183),
    BIRCH_FENCE_GATE("minecraft:birch_fence_gate", 184),
    JUNGLE_FENCE_GATE("minecraft:jungle_fence_gate", 185),
    DARK_OAK_FENCE_GATE("minecraft:dark_oak_fence_gate", 186),
    ACACIA_FENCE_GATE("minecraft:acacia_fence_gate", 187),
    SPRUCE_FENCE("minecraft:spruce_fence", 188),
    BIRCH_FENCE("minecraft:birch_fence", 189),
    JUNGLE_FENCE("minecraft:jungle_fence", 190),
    DARK_OAK_FENCE("minecraft:dark_oak_fence", 191),
    ACACIA_FENCE("minecraft:acacia_fence", 192),
    SPRUCE_DOOR_BLOCK("minecraft:spruce_door", 193),
    BIRCH_DOOR_BLOCK("minecraft:birch_door", 194),
    JUNGLE_DOOR_BLOCK("minecraft:jungle_door", 195),
    ACACIA_DOOR_BLOCK("minecraft:acacia_door", 196),
    DARK_OAK_DOOR_BLOCK("minecraft:dark_oak_door", 197),
    END_ROD("minecraft:end_rod", 198),
    CHORUS_PLANT("minecraft:chorus_plant", 199),
    CHORUS_FLOWER("minecraft:chorus_flower", 200),
    PURPUR_BLOCK("minecraft:purpur_block", 201),
    PURPUR_PILLAR("minecraft:purpur_pillar", 202),
    PURPUR_STAIRS("minecraft:purpur_stairs", 203),
    PURPUR_DOUBLE_SLAB("minecraft:purpur_double_slab", 204),
    PURPUR_SLAB("minecraft:purpur_slab", 205),
    END_STONE_BRICKS("minecraft:end_bricks", 206),
    BEETROOT_BLOCK("minecraft:beetroots", 207),
    GRASS_PATH("minecraft:grass_path", 208),
    END_GATEWAY("minecraft:end_gateway", 209),
    REPEATING_COMMAND_BLOCK("minecraft:repeating_command_block", 210),
    CHAIN_COMMAND_BLOCK("minecraft:chain_command_block", 211),
    FROSTED_ICE("minecraft:frosted_ice", 212),
    MAGMA_BLOCK("minecraft:magma", 213),
    NETHER_WART_BLOCK("minecraft:nether_wart_block", 214),
    RED_NETHER_BRICK("minecraft:red_nether_brick", 215),
    BONE_BLOCK("minecraft:bone_block", 216),
    STRUCTURE_VOID("minecraft:structure_void", 217),
    OBSERVER("minecraft:observer", 218),
    WHITE_SHULKER_BOX("minecraft:white_shulker_box", 219),
    ORANGE_SHULKER_BOX("minecraft:orange_shulker_box", 220),
    MAGENTA_SHULKER_BOX("minecraft:magenta_shulker_box", 221),
    LIGHT_BLUE_SHULKER_BOX("minecraft:light_blue_shulker_box", 222),
    YELLOW_SHULKER_BOX("minecraft:yellow_shulker_box", 223),
    LIME_SHULKER_BOX("minecraft:lime_shulker_box", 224),
    PINK_SHULKER_BOX("minecraft:pink_shulker_box", 225),
    GRAY_SHULKER_BOX("minecraft:gray_shulker_box", 226),
    LIGHT_GRAY_SHULKER_BOX("minecraft:silver_shulker_box", 227),
    CYAN_SHULKER_BOX("minecraft:cyan_shulker_box", 228),
    PURPLE_SHULKER_BOX("minecraft:purple_shulker_box", 229),
    BLUE_SHULKER_BOX("minecraft:blue_shulker_box", 230),
    BROWN_SHULKER_BOX("minecraft:brown_shulker_box", 231),
    GREEN_SHULKER_BOX("minecraft:green_shulker_box", 232),
    RED_SHULKER_BOX("minecraft:red_shulker_box", 233),
    BLACK_SHULKER_BOX("minecraft:black_shulker_box", 234),
    WHITE_GLAZED_TERRACOTTA("minecraft:white_glazed_terracotta", 235),
    ORANGE_GLAZED_TERRACOTTA("minecraft:orange_glazed_terracotta", 236),
    MAGENTA_GLAZED_TERRACOTTA("minecraft:magenta_glazed_terracotta", 237),
    LIGHT_BLUE_GLAZED_TERRACOTTA("minecraft:light_blue_glazed_terracotta", 238),
    YELLOW_GLAZED_TERRACOTTA("minecraft:yellow_glazed_terracotta", 239),
    LIME_GLAZED_TERRACOTTA("minecraft:lime_glazed_terracotta", 240),
    PINK_GLAZED_TERRACOTTA("minecraft:pink_glazed_terracotta", 241),
    GRAY_GLAZED_TERRACOTTA("minecraft:gray_glazed_terracotta", 242),
    LIGHT_GRAY_GLAZED_TERRACOTTA("minecraft:light_gray_glazed_terracotta", 243),
    CYAN_GLAZED_TERRACOTTA("minecraft:cyan_glazed_terracotta", 244),
    PURPLE_GLAZED_TERRACOTTA("minecraft:purple_glazed_terracotta", 245),
    BLUE_GLAZED_TERRACOTTA("minecraft:blue_glazed_terracotta", 246),
    BROWN_GLAZED_TERRACOTTA("minecraft:brown_glazed_terracotta", 247),
    GREEN_GLAZED_TERRACOTTA("minecraft:green_glazed_terracotta", 248),
    RED_GLAZED_TERRACOTTA("minecraft:red_glazed_terracotta", 249),
    BLACK_GLAZED_TERRACOTTA("minecraft:black_glazed_terracotta", 250),
    WHITE_CONCRETE("minecraft:concrete", 251),
    ORANGE_CONCRETE("minecraft:concrete", 251, 1),
    MAGENTA_CONCRETE("minecraft:concrete", 251, 2),
    LIGHT_BLUE_CONCRETE("minecraft:concrete", 251, 3),
    YELLOW_CONCRETE("minecraft:concrete", 251, 4),
    LIME_CONCRETE("minecraft:concrete", 251, 5),
    PINK_CONCRETE("minecraft:concrete", 251, 6),
    GRAY_CONCRETE("minecraft:concrete", 251, 7),
    LIGHT_GRAY_CONCRETE("minecraft:concrete", 251, 8),
    CYAN_CONCRETE("minecraft:concrete", 251, 9),
    PURPLE_CONCRETE("minecraft:concrete", 251, 10),
    BLUE_CONCRETE("minecraft:concrete", 251, 11),
    BROWN_CONCRETE("minecraft:concrete", 251, 12),
    GREEN_CONCRETE("minecraft:concrete", 251, 13),
    RED_CONCRETE("minecraft:concrete", 251, 14),
    BLACK_CONCRETE("minecraft:concrete", 251, 15),
    WHITE_CONCRETE_POWDER("minecraft:concrete_powder", 252),
    ORANGE_CONCRETE_POWDER("minecraft:concrete_powder", 252, 1),
    MAGENTA_CONCRETE_POWDER("minecraft:concrete_powder", 252, 2),
    LIGHT_BLUE_CONCRETE_POWDER("minecraft:concrete_powder", 252, 3),
    YELLOW_CONCRETE_POWDER("minecraft:concrete_powder", 252, 4),
    LIME_CONCRETE_POWDER("minecraft:concrete_powder", 252, 5),
    PINK_CONCRETE_POWDER("minecraft:concrete_powder", 252, 6),
    GRAY_CONCRETE_POWDER("minecraft:concrete_powder", 252, 7),
    LIGHT_GRAY_CONCRETE_POWDER("minecraft:concrete_powder", 252, 8),
    CYAN_CONCRETE_POWDER("minecraft:concrete_powder", 252, 9),
    PURPLE_CONCRETE_POWDER("minecraft:concrete_powder", 252, 10),
    BLUE_CONCRETE_POWDER("minecraft:concrete_powder", 252, 11),
    BROWN_CONCRETE_POWDER("minecraft:concrete_powder", 252, 12),
    GREEN_CONCRETE_POWDER("minecraft:concrete_powder", 252, 13),
    RED_CONCRETE_POWDER("minecraft:concrete_powder", 252, 14),
    BLACK_CONCRETE_POWDER("minecraft:concrete_powder", 252, 15),
    STRUCTURE_BLOCK("minecraft:structure_block", 255),
    IRON_SHOVEL("minecraft:iron_shovel", 256),
    IRON_PICKAXE("minecraft:iron_pickaxe", 257),
    IRON_AXE("minecraft:iron_axe", 258),
    FLINT_AND_STEEL("minecraft:flint_and_steel", 259),
    APPLE("minecraft:apple", 260),
    BOW("minecraft:bow", 261),
    ARROW("minecraft:arrow", 262),
    COAL("minecraft:coal", 263),
    CHARCOAL("minecraft:coal", 263, 1),
    DIAMOND("minecraft:diamond", 264),
    IRON_INGOT("minecraft:iron_ingot", 265),
    GOLD_INGOT("minecraft:gold_ingot", 266),
    IRON_SWORD("minecraft:iron_sword", 267),
    WOOD_SWORD("minecraft:wooden_sword", 268),
    WOOD_SHOVEL("minecraft:wooden_shovel", 269),
    WOOD_PICKAXE("minecraft:wooden_pickaxe", 270),
    WOOD_AXE("minecraft:wooden_axe", 271),
    STONE_SWORD("minecraft:stone_sword", 272),
    STONE_SHOVEL("minecraft:stone_shovel", 273),
    STONE_PICKAXE("minecraft:stone_pickaxe", 274),
    STONE_AXE("minecraft:stone_axe", 275),
    DIAMOND_SWORD("minecraft:diamond_sword", 276),
    DIAMOND_SHOVEL("minecraft:diamond_shovel", 277),
    DIAMOND_PICKAXE("minecraft:diamond_pickaxe", 278),
    DIAMOND_AXE("minecraft:diamond_axe", 279),
    STICK("minecraft:stick", 280),
    BOWL("minecraft:bowl", 281),
    MUSHROOM_STEW("minecraft:mushroom_stew", 282),
    GOLD_SWORD("minecraft:golden_sword", 283),
    GOLD_SHOVEL("minecraft:golden_shovel", 284),
    GOLD_PICKAXE("minecraft:golden_pickaxe", 285),
    GOLD_AXE("minecraft:golden_axe", 286),
    STRING("minecraft:string", 287),
    FEATHER("minecraft:feather", 288),
    GUNPOWDER("minecraft:gunpowder", 289),
    WOOD_HOE("minecraft:wooden_hoe", 290),
    STONE_HOE("minecraft:stone_hoe", 291),
    IRON_HOE("minecraft:iron_hoe", 292),
    DIAMOND_HOE("minecraft:diamond_hoe", 293),
    GOLD_HOE("minecraft:golden_hoe", 294),
    WHEAT_SEEDS("minecraft:wheat_seeds", 295),
    WHEAT("minecraft:wheat", 296),
    BREAD("minecraft:bread", 297),
    LEATHER_HELMET("minecraft:leather_helmet", 298),
    LEATHER_TUNIC("minecraft:leather_chestplate", 299),
    LEATHER_PANTS("minecraft:leather_leggings", 300),
    LEATHER_BOOTS("minecraft:leather_boots", 301),
    CHAINMAIL_HELMET("minecraft:chainmail_helmet", 302),
    CHAINMAIL_CHESTPLATE("minecraft:chainmail_chestplate", 303),
    CHAINMAIL_LEGGINGS("minecraft:chainmail_leggings", 304),
    CHAINMAIL_BOOTS("minecraft:chainmail_boots", 305),
    IRON_HELMET("minecraft:iron_helmet", 306),
    IRON_CHESTPLATE("minecraft:iron_chestplate", 307),
    IRON_LEGGINGS("minecraft:iron_leggings", 308),
    IRON_BOOTS("minecraft:iron_boots", 309),
    DIAMOND_HELMET("minecraft:diamond_helmet", 310),
    DIAMOND_CHESTPLATE("minecraft:diamond_chestplate", 311),
    DIAMOND_LEGGINGS("minecraft:diamond_leggings", 312),
    DIAMOND_BOOTS("minecraft:diamond_boots", 313),
    GOLD_HELMET("minecraft:golden_helmet", 314),
    GOLD_CHESTPLATE("minecraft:golden_chestplate", 315),
    GOLD_LEGGINGS("minecraft:golden_leggings", 316),
    GOLD_BOOTS("minecraft:golden_boots", 317),
    FLINT("minecraft:flint", 318),
    RAW_PORKCHOP("minecraft:porkchop", 319),
    COOKED_PORKCHOP("minecraft:cooked_porkchop", 320),
    PAINTING("minecraft:painting", 321),
    GOLD_APPLE("minecraft:golden_apple", 322),
    ENCHANTED_GOLD_APPLE("minecraft:golden_apple", 322, 1),
    SIGN("minecraft:sign", 323),
    OAK_DOOR("minecraft:wooden_door", 324),
    BUCKET("minecraft:bucket", 325),
    WATER_BUCKET("minecraft:water_bucket", 326),
    LAVA_BUCKET("minecraft:lava_bucket", 327),
    MINECART("minecraft:minecart", 328),
    SADDLE("minecraft:saddle", 329),
    IRON_DOOR("minecraft:iron_door", 330),
    REDSTONE("minecraft:redstone", 331),
    SNOWBALL("minecraft:snowball", 332),
    OAK_BOAT("minecraft:boat", 333),
    LEATHER("minecraft:leather", 334),
    MILK_BUCKET("minecraft:milk_bucket", 335),
    BRICK("minecraft:brick", 336),
    CLAY_BALL("minecraft:clay_ball", 337),
    SUGAR_CANES("minecraft:reeds", 338),
    PAPER("minecraft:paper", 339),
    BOOK("minecraft:book", 340),
    SLIMEBALL("minecraft:slime_ball", 341),
    MINECART_WITH_CHEST("minecraft:chest_minecart", 342),
    MINECART_WITH_FURNACE("minecraft:furnace_minecart", 343),
    EGG("minecraft:egg", 344),
    COMPASS("minecraft:compass", 345),
    FISHING_ROD("minecraft:fishing_rod", 346),
    CLOCK("minecraft:clock", 347),
    GLOWSTONE_DUST("minecraft:glowstone_dust", 348),
    RAW_FISH("minecraft:fish", 349),
    RAW_SALMON("minecraft:fish", 349, 1),
    CLOWNFISH("minecraft:fish", 349, 2),
    PUFFERFISH("minecraft:fish", 349, 3),
    COOKED_FISH("minecraft:cooked_fish", 350),
    COOKED_SALMON("minecraft:cooked_fish", 350, 1),
    INK_SACK("minecraft:dye", 351),
    ROSE_RED("minecraft:dye", 351, 1),
    CACTUS_GREEN("minecraft:dye", 351, 2),
    COCO_BEANS("minecraft:dye", 351, 3),
    LAPIS_LAZULI("minecraft:dye", 351, 4),
    PURPLE_DYE("minecraft:dye", 351, 5),
    CYAN_DYE("minecraft:dye", 351, 6),
    LIGHT_GRAY_DYE("minecraft:dye", 351, 7),
    GRAY_DYE("minecraft:dye", 351, 8),
    PINK_DYE("minecraft:dye", 351, 9),
    LIME_DYE("minecraft:dye", 351, 10),
    DANDELION_YELLOW("minecraft:dye", 351, 11),
    LIGHT_BLUE_DYE("minecraft:dye", 351, 12),
    MAGENTA_DYE("minecraft:dye", 351, 13),
    ORANGE_DYE("minecraft:dye", 351, 14),
    BONE_MEAL("minecraft:dye", 351, 15),
    BONE("minecraft:bone", 352),
    SUGAR("minecraft:sugar", 353),
    CAKE("minecraft:cake", 354),
    WHITE_BED("minecraft:bed", 355),
    ORANGE_BED("minecraft:bed", 355, 1),
    MAGENTA_BED("minecraft:bed", 355, 2),
    LIGHT_BLUE_BED("minecraft:bed", 355, 3),
    YELLOW_BED("minecraft:bed", 355, 4),
    LIME_BED("minecraft:bed", 355, 5),
    PINK_BED("minecraft:bed", 355, 6),
    GRAY_BED("minecraft:bed", 355, 7),
    LIGHT_GRAY_BED("minecraft:bed", 355, 8),
    CYAN_BED("minecraft:bed", 355, 9),
    PURPLE_BED("minecraft:bed", 355, 10),
    BLUE_BED("minecraft:bed", 355, 11),
    BROWN_BED("minecraft:bed", 355, 12),
    GREEN_BED("minecraft:bed", 355, 13),
    RED_BED("minecraft:bed", 355, 14),
    BLACK_BED("minecraft:bed", 355, 15),
    REDSTONE_REPEATER("minecraft:repeater", 356),
    COOKIE("minecraft:cookie", 357),
    MAP("minecraft:filled_map", 358),
    SHEARS("minecraft:shears", 359),
    MELON("minecraft:melon", 360),
    PUMPKIN_SEEDS("minecraft:pumpkin_seeds", 361),
    MELON_SEEDS("minecraft:melon_seeds", 362),
    RAW_BEEF("minecraft:beef", 363),
    STEAK("minecraft:cooked_beef", 364),
    RAW_CHICKEN("minecraft:chicken", 365),
    COOKED_CHICKEN("minecraft:cooked_chicken", 366),
    ROTTEN_FLESH("minecraft:rotten_flesh", 367),
    ENDER_PEARL("minecraft:ender_pearl", 368),
    BLAZE_ROD("minecraft:blaze_rod", 369),
    GHAST_TEAR("minecraft:ghast_tear", 370),
    GOLD_NUGGET("minecraft:gold_nugget", 371),
    NETHER_WART("minecraft:nether_wart", 372),
    POTION("minecraft:potion", 373),
    GLASS_BOTTLE("minecraft:glass_bottle", 374),
    SPIDER_EYE("minecraft:spider_eye", 375),
    FERMENTED_SPIDER_EYE("minecraft:fermented_spider_eye", 376),
    BLAZE_POWDER("minecraft:blaze_powder", 377),
    MAGMA_CREAM("minecraft:magma_cream", 378),
    BREWING_STAND("minecraft:brewing_stand", 379),
    CAULDRON("minecraft:cauldron", 380),
    EYE_OF_ENDER("minecraft:ender_eye", 381),
    GLISTERING_MELON("minecraft:speckled_melon", 382),
    SPAWN_ELDER_GUARDIAN("minecraft:spawn_egg", 383, 4),
    SPAWN_WITHER_SKELETON("minecraft:spawn_egg", 383, 5),
    SPAWN_STRAY("minecraft:spawn_egg", 383, 6),
    SPAWN_HUSK("minecraft:spawn_egg", 383, 23),
    SPAWN_ZOMBIE_VILLAGER("minecraft:spawn_egg", 383, 27),
    SPAWN_SKELETON_HORSE("minecraft:spawn_egg", 383, 28),
    SPAWN_ZOMBIE_HORSE("minecraft:spawn_egg", 383, 29),
    SPAWN_DONKEY("minecraft:spawn_egg", 383, 31),
    SPAWN_MULE("minecraft:spawn_egg", 383, 32),
    SPAWN_EVOKER("minecraft:spawn_egg", 383, 34),
    SPAWN_VEX("minecraft:spawn_egg", 383, 35),
    SPAWN_VINDICATOR("minecraft:spawn_egg", 383, 36),
    SPAWN_CREEPER("minecraft:spawn_egg", 383, 50),
    SPAWN_SKELETON("minecraft:spawn_egg", 383, 51),
    SPAWN_SPIDER("minecraft:spawn_egg", 383, 52),
    SPAWN_ZOMBIE("minecraft:spawn_egg", 383, 54),
    SPAWN_SLIME("minecraft:spawn_egg", 383, 55),
    SPAWN_GHAST("minecraft:spawn_egg", 383, 56),
    SPAWN_ZOMBIE_PIGMAN("minecraft:spawn_egg", 383, 57),
    SPAWN_ENDERMAN("minecraft:spawn_egg", 383, 58),
    SPAWN_CAVE_SPIDER("minecraft:spawn_egg", 383, 59),
    SPAWN_SILVERFISH("minecraft:spawn_egg", 383, 60),
    SPAWN_BLAZE("minecraft:spawn_egg", 383, 61),
    SPAWN_MAGMA_CUBE("minecraft:spawn_egg", 383, 62),
    SPAWN_BAT("minecraft:spawn_egg", 383, 65),
    SPAWN_WITCH("minecraft:spawn_egg", 383, 66),
    SPAWN_ENDERMITE("minecraft:spawn_egg", 383, 67),
    SPAWN_GUARDIAN("minecraft:spawn_egg", 383, 68),
    SPAWN_SHULKER("minecraft:spawn_egg", 383, 69),
    SPAWN_PIG("minecraft:spawn_egg", 383, 90),
    SPAWN_SHEEP("minecraft:spawn_egg", 383, 91),
    SPAWN_COW("minecraft:spawn_egg", 383, 92),
    SPAWN_CHICKEN("minecraft:spawn_egg", 383, 93),
    SPAWN_SQUID("minecraft:spawn_egg", 383, 94),
    SPAWN_WOLF("minecraft:spawn_egg", 383, 95),
    SPAWN_MOOSHROOM("minecraft:spawn_egg", 383, 96),
    SPAWN_OCELOT("minecraft:spawn_egg", 383, 98),
    SPAWN_HORSE("minecraft:spawn_egg", 383, 100),
    SPAWN_RABBIT("minecraft:spawn_egg", 383, 101),
    SPAWN_POLAR_BEAR("minecraft:spawn_egg", 383, 102),
    SPAWN_LLAMA("minecraft:spawn_egg", 383, 103),
    SPAWN_PARROT("minecraft:spawn_egg", 383, 105),
    SPAWN_VILLAGER("minecraft:spawn_egg", 383, 120),
    BOTTLE_O_ENCHANTING("minecraft:experience_bottle", 384),
    FIRE_CHARGE("minecraft:fire_charge", 385),
    BOOK_AND_QUILL("minecraft:writable_book", 386),
    WRITTEN_BOOK("minecraft:written_book", 387),
    EMERALD("minecraft:emerald", 388),
    ITEM_FRAME("minecraft:item_frame", 389),
    FLOWER_POT("minecraft:flower_pot", 390),
    CARROT("minecraft:carrot", 391),
    POTATO("minecraft:potato", 392),
    BAKED_POTATO("minecraft:baked_potato", 393),
    POISONOUS_POTATO("minecraft:poisonous_potato", 394),
    EMPTY_MAP("minecraft:map", 395),
    GOLD_CARROT("minecraft:golden_carrot", 396),
    MOB_HEAD_SKELETON("minecraft:skull", 397),
    MOB_HEAD_WITHER_SKELETON("minecraft:skull", 397, 1),
    MOB_HEAD_ZOMBIE("minecraft:skull", 397, 2),
    MOB_HEAD_HUMAN("minecraft:skull", 397, 3),
    MOB_HEAD_CREEPER("minecraft:skull", 397, 4),
    MOB_HEAD_DRAGON("minecraft:skull", 397, 5),
    CARROT_ON_A_STICK("minecraft:carrot_on_a_stick", 398),
    NETHER_STAR("minecraft:nether_star", 399),
    PUMPKIN_PIE("minecraft:pumpkin_pie", 400),
    FIREWORK_ROCKET("minecraft:fireworks", 401),
    FIREWORK_STAR("minecraft:firework_charge", 402),
    ENCHANTED_BOOK("minecraft:enchanted_book", 403),
    REDSTONE_COMPARATOR("minecraft:comparator", 404),
    NETHER_BRICK("minecraft:netherbrick", 405),
    NETHER_QUARTZ("minecraft:quartz", 406),
    MINECART_WITH_TNT("minecraft:tnt_minecart", 407),
    MINECART_WITH_HOPPER("minecraft:hopper_minecart", 408),
    PRISMARINE_SHARD("minecraft:prismarine_shard", 409),
    PRISMARINE_CRYSTALS("minecraft:prismarine_crystals", 410),
    RAW_RABBIT("minecraft:rabbit", 411),
    COOKED_RABBIT("minecraft:cooked_rabbit", 412),
    RABBIT_STEW("minecraft:rabbit_stew", 413),
    RABBITS_FOOT("minecraft:rabbit_foot", 414),
    RABBIT_HIDE("minecraft:rabbit_hide", 415),
    ARMOR_STAND("minecraft:armor_stand", 416),
    IRON_HORSE_ARMOR("minecraft:iron_horse_armor", 417),
    GOLD_HORSE_ARMOR("minecraft:golden_horse_armor", 418),
    DIAMOND_HORSE_ARMOR("minecraft:diamond_horse_armor", 419),
    LEAD("minecraft:lead", 420),
    NAME_TAG("minecraft:name_tag", 421),
    MINECART_WITH_COMMAND_BLOCK("minecraft:command_block_minecart", 422),
    RAW_MUTTON("minecraft:mutton", 423),
    COOKED_MUTTON("minecraft:cooked_mutton", 424),
    BANNER("minecraft:banner", 425),
    END_CRYSTAL("minecraft:end_crystal", 426),
    SPRUCE_DOOR("minecraft:spruce_door", 427),
    BIRCH_DOOR("minecraft:birch_door", 428),
    JUNGLE_DOOR("minecraft:jungle_door", 429),
    ACACIA_DOOR("minecraft:acacia_door", 430),
    DARK_OAK_DOOR("minecraft:dark_oak_door", 431),
    CHORUS_FRUIT("minecraft:chorus_fruit", 432),
    POPPED_CHORUS_FRUIT("minecraft:popped_chorus_fruit", 433),
    BEETROOT("minecraft:beetroot", 434),
    BEETROOT_SEEDS("minecraft:beetroot_seeds", 435),
    BEETROOT_SOUP("minecraft:beetroot_soup", 436),
    DRAGONS_BREATH("minecraft:dragon_breath", 437),
    SPLASH_POTION("minecraft:splash_potion", 438),
    SPECTRAL_ARROW("minecraft:spectral_arrow", 439),
    TIPPED_ARROW("minecraft:tipped_arrow", 440),
    LINGERING_POTION("minecraft:lingering_potion", 441),
    SHIELD("minecraft:shield", 442),
    ELYTRA("minecraft:elytra", 443),
    SPRUCE_BOAT("minecraft:spruce_boat", 444),
    BIRCH_BOAT("minecraft:birch_boat", 445),
    JUNGLE_BOAT("minecraft:jungle_boat", 446),
    ACACIA_BOAT("minecraft:acacia_boat", 447),
    DARK_OAK_BOAT("minecraft:dark_oak_boat", 448),
    TOTEM_OF_UNDYING("minecraft:totem_of_undying", 449),
    SHULKER_SHELL("minecraft:shulker_shell", 450),
    IRON_NUGGET("minecraft:iron_nugget", 452),
    KNOWLEDGE_BOOK("minecraft:knowledge_book", 453),
    THIRTEEN_DISC("minecraft:record_13", 2256),
    CAT_DISC("minecraft:record_cat", 2257),
    BLOCKS_DISC("minecraft:record_blocks", 2258),
    CHIRP_DISC("minecraft:record_chirp", 2259),
    FAR_DISC("minecraft:record_far", 2260),
    MALL_DISC("minecraft:record_mall", 2261),
    MELLOHI_DISC("minecraft:record_mellohi", 2262),
    STAL_DISC("minecraft:record_stal", 2263),
    STRAD_DISC("minecraft:record_strad", 2264),
    WARD_DISC("minecraft:record_ward", 2265),
    ELEVEN_DISC("minecraft:record_11", 2266),
    WAIT_DISC("minecraft:record_wait", 2267);

    private final String type;
    private final int id;
    private final byte data;

    ItemType(final String type, final int id) {
        this(type, id, 0);
    }

    ItemType(final String type, final int id, final int data) {
        this.type = type;
        this.id = id;
        this.data = (byte) data;
    }

    /**
     * @return The Minecraft type of the item type.
     */
    public String getType() {
        return type;
    }

    /**
     * @return The Minecraft id of the item type.
     */
    public int getId() {
        return id;
    }

    /**
     * @return The Minecraft data of the item type.
     */
    public int getData() {
        return data;
    }
}
