package gg.warcraft.monolith.spigot.entity;

import gg.warcraft.monolith.api.entity.EntityType;

public class SpigotEntityTypeMapper {

    public EntityType map(org.bukkit.entity.EntityType type) {
        switch (type) {
            case DROPPED_ITEM:
                return EntityType.DROPPED_ITEM;
            case EXPERIENCE_ORB:
                return EntityType.EXPERIENCE_ORB;
            case AREA_EFFECT_CLOUD:
                return EntityType.AREA_EFFECT_CLOUD;
            case ELDER_GUARDIAN:
                return EntityType.ELDER_GUARDIAN;
            case WITHER_SKELETON:
                return EntityType.WITHER_SKELETON;
            case STRAY:
                return EntityType.STRAY;
            case EGG:
                return EntityType.EGG;
            case LEASH_HITCH:
                return EntityType.LEAD_KNOT;
            case PAINTING:
                return EntityType.PAINTING;
            case ARROW:
                return EntityType.ARROW;
            case SNOWBALL:
                return EntityType.SNOWBALL;
            case FIREBALL:
                return EntityType.GHAST_FIREBALL;
            case SMALL_FIREBALL:
                return EntityType.BLAZE_FIREBALL;
            case ENDER_PEARL:
                return EntityType.ENDER_PEARL;
            case ENDER_SIGNAL:
                return EntityType.EYE_OF_ENDER;
            case SPLASH_POTION:
                return EntityType.SPLASH_POTION;
            case THROWN_EXP_BOTTLE:
                return EntityType.BOTTLE_O_ENCHANTING;
            case ITEM_FRAME:
                return EntityType.ITEM_FRAME;
            case WITHER_SKULL:
                return EntityType.WITHER_SKULL;
            case PRIMED_TNT:
                return EntityType.PRIMED_TNT;
            case FALLING_BLOCK:
                return EntityType.FALLING_BLOCK;
            case FIREWORK:
                return EntityType.FIREWORK_ROCKET;
            case HUSK:
                return EntityType.HUSK;
            case SPECTRAL_ARROW:
                return EntityType.SPECTRAL_ARROW;
            case SHULKER_BULLET:
                return EntityType.SHULKER_BULLET;
            case DRAGON_FIREBALL:
                return EntityType.DRAGON_FIREBALL;
            case ZOMBIE_VILLAGER:
                return EntityType.ZOMBIE_VILLAGER;
            case SKELETON_HORSE:
                return EntityType.SKELETON_HORSE;
            case ZOMBIE_HORSE:
                return EntityType.ZOMBIE_HORSE;
            case ARMOR_STAND:
                return EntityType.ARMOR_STAND;
            case DONKEY:
                return EntityType.DONKEY;
            case MULE:
                return EntityType.MULE;
            case EVOKER_FANGS:
                return EntityType.EVOCATION_FANGS;
            case EVOKER:
                return EntityType.EVOKER;
            case VEX:
                return EntityType.VEX;
            case VINDICATOR:
                return EntityType.VINDICATOR;
            case ILLUSIONER:
                return EntityType.ILLUSIONER;
            case MINECART_COMMAND:
                return EntityType.MINECART_WITH_COMMAND_BLOCK;
            case BOAT:
                return EntityType.BOAT;
            case MINECART:
                return EntityType.MINECART;
            case MINECART_CHEST:
                return EntityType.STORAGE_MINECART;
            case MINECART_FURNACE:
                return EntityType.POWERED_MINECART;
            case MINECART_TNT:
                return EntityType.MINECART_WITH_TNT;
            case MINECART_HOPPER:
                return EntityType.MINECART_WITH_HOPPER;
            case MINECART_MOB_SPAWNER:
                return EntityType.MINECART_WITH_SPAWNER;
            case CREEPER:
                return EntityType.CREEPER;
            case SKELETON:
                return EntityType.SKELETON;
            case SPIDER:
                return EntityType.SPIDER;
            case GIANT:
                return EntityType.GIANT_ZOMBIE;
            case ZOMBIE:
                return EntityType.ZOMBIE;
            case SLIME:
                return EntityType.SLIME;
            case GHAST:
                return EntityType.GHAST;
            case PIG_ZOMBIE:
                return EntityType.ZOMBIE_PIGMAN;
            case ENDERMAN:
                return EntityType.ENDERMAN;
            case CAVE_SPIDER:
                return EntityType.CAVE_SPIDER;
            case SILVERFISH:
                return EntityType.SILVERFISH;
            case BLAZE:
                return EntityType.BLAZE;
            case MAGMA_CUBE:
                return EntityType.MAGMA_CUBE;
            case ENDER_DRAGON:
                return EntityType.ENDER_DRAGON;
            case WITHER:
                return EntityType.WITHER;
            case BAT:
                return EntityType.BAT;
            case WITCH:
                return EntityType.WITCH;
            case ENDERMITE:
                return EntityType.ENDERMITE;
            case GUARDIAN:
                return EntityType.GUARDIAN;
            case SHULKER:
                return EntityType.SHULKER;
            case PIG:
                return EntityType.PIG;
            case SHEEP:
                return EntityType.SHEEP;
            case COW:
                return EntityType.COW;
            case CHICKEN:
                return EntityType.CHICKEN;
            case SQUID:
                return EntityType.SQUID;
            case WOLF:
                return EntityType.WOLF;
            case MUSHROOM_COW:
                return EntityType.MOOSHROOM;
            case SNOWMAN:
                return EntityType.SNOW_GOLEM;
            case OCELOT:
                return EntityType.OCELOT;
            case IRON_GOLEM:
                return EntityType.IRON_GOLEM;
            case HORSE:
                return EntityType.HORSE;
            case RABBIT:
                return EntityType.RABBIT;
            case POLAR_BEAR:
                return EntityType.POLAR_BEAR;
            case LLAMA:
                return EntityType.LLAMA;
            case LLAMA_SPIT:
                return EntityType.LLAMA_SPIT;
            case PARROT:
                return EntityType.PARROT;
            case VILLAGER:
                return EntityType.VILLAGER;
            case ENDER_CRYSTAL:
                return EntityType.ENDER_CRYSTAL;
            case PLAYER:
                return EntityType.PLAYER;
            default:
                throw new IllegalArgumentException("Unsupported entity type: " + type);
        }
    }

    public org.bukkit.entity.EntityType map(EntityType type) {
        switch (type) {
            case DROPPED_ITEM:
                return org.bukkit.entity.EntityType.DROPPED_ITEM;
            case EXPERIENCE_ORB:
                return org.bukkit.entity.EntityType.EXPERIENCE_ORB;
            case AREA_EFFECT_CLOUD:
                return org.bukkit.entity.EntityType.AREA_EFFECT_CLOUD;
            case ELDER_GUARDIAN:
                return org.bukkit.entity.EntityType.ELDER_GUARDIAN;
            case WITHER_SKELETON:
                return org.bukkit.entity.EntityType.WITHER_SKELETON;
            case STRAY:
                return org.bukkit.entity.EntityType.STRAY;
            case EGG:
                return org.bukkit.entity.EntityType.EGG;
            case LEAD_KNOT:
                return org.bukkit.entity.EntityType.LEASH_HITCH;
            case PAINTING:
                return org.bukkit.entity.EntityType.PAINTING;
            case ARROW:
                return org.bukkit.entity.EntityType.ARROW;
            case SNOWBALL:
                return org.bukkit.entity.EntityType.SNOWBALL;
            case GHAST_FIREBALL:
                return org.bukkit.entity.EntityType.FIREBALL;
            case BLAZE_FIREBALL:
                return org.bukkit.entity.EntityType.SMALL_FIREBALL;
            case ENDER_PEARL:
                return org.bukkit.entity.EntityType.ENDER_PEARL;
            case EYE_OF_ENDER:
                return org.bukkit.entity.EntityType.ENDER_SIGNAL;
            case SPLASH_POTION:
                return org.bukkit.entity.EntityType.SPLASH_POTION;
            case BOTTLE_O_ENCHANTING:
                return org.bukkit.entity.EntityType.THROWN_EXP_BOTTLE;
            case ITEM_FRAME:
                return org.bukkit.entity.EntityType.ITEM_FRAME;
            case WITHER_SKULL:
                return org.bukkit.entity.EntityType.WITHER_SKULL;
            case PRIMED_TNT:
                return org.bukkit.entity.EntityType.PRIMED_TNT;
            case FALLING_BLOCK:
                return org.bukkit.entity.EntityType.FALLING_BLOCK;
            case FIREWORK_ROCKET:
                return org.bukkit.entity.EntityType.FIREWORK;
            case HUSK:
                return org.bukkit.entity.EntityType.HUSK;
            case SPECTRAL_ARROW:
                return org.bukkit.entity.EntityType.SPECTRAL_ARROW;
            case SHULKER_BULLET:
                return org.bukkit.entity.EntityType.SHULKER_BULLET;
            case DRAGON_FIREBALL:
                return org.bukkit.entity.EntityType.DRAGON_FIREBALL;
            case ZOMBIE_VILLAGER:
                return org.bukkit.entity.EntityType.ZOMBIE_VILLAGER;
            case SKELETON_HORSE:
                return org.bukkit.entity.EntityType.SKELETON_HORSE;
            case ZOMBIE_HORSE:
                return org.bukkit.entity.EntityType.ZOMBIE_HORSE;
            case ARMOR_STAND:
                return org.bukkit.entity.EntityType.ARMOR_STAND;
            case DONKEY:
                return org.bukkit.entity.EntityType.DONKEY;
            case MULE:
                return org.bukkit.entity.EntityType.MULE;
            case EVOCATION_FANGS:
                return org.bukkit.entity.EntityType.EVOKER_FANGS;
            case EVOKER:
                return org.bukkit.entity.EntityType.EVOKER;
            case VEX:
                return org.bukkit.entity.EntityType.VEX;
            case VINDICATOR:
                return org.bukkit.entity.EntityType.VINDICATOR;
            case ILLUSIONER:
                return org.bukkit.entity.EntityType.ILLUSIONER;
            case MINECART_WITH_COMMAND_BLOCK:
                return org.bukkit.entity.EntityType.MINECART_COMMAND;
            case BOAT:
                return org.bukkit.entity.EntityType.BOAT;
            case MINECART:
                return org.bukkit.entity.EntityType.MINECART;
            case STORAGE_MINECART:
                return org.bukkit.entity.EntityType.MINECART_CHEST;
            case POWERED_MINECART:
                return org.bukkit.entity.EntityType.MINECART_FURNACE;
            case MINECART_WITH_TNT:
                return org.bukkit.entity.EntityType.MINECART_TNT;
            case MINECART_WITH_HOPPER:
                return org.bukkit.entity.EntityType.MINECART_HOPPER;
            case MINECART_WITH_SPAWNER:
                return org.bukkit.entity.EntityType.MINECART_MOB_SPAWNER;
            case CREEPER:
                return org.bukkit.entity.EntityType.CREEPER;
            case SKELETON:
                return org.bukkit.entity.EntityType.SKELETON;
            case SPIDER:
                return org.bukkit.entity.EntityType.SPIDER;
            case GIANT_ZOMBIE:
                return org.bukkit.entity.EntityType.GIANT;
            case ZOMBIE:
                return org.bukkit.entity.EntityType.ZOMBIE;
            case SLIME:
                return org.bukkit.entity.EntityType.SLIME;
            case GHAST:
                return org.bukkit.entity.EntityType.GHAST;
            case ZOMBIE_PIGMAN:
                return org.bukkit.entity.EntityType.PIG_ZOMBIE;
            case ENDERMAN:
                return org.bukkit.entity.EntityType.ENDERMAN;
            case CAVE_SPIDER:
                return org.bukkit.entity.EntityType.CAVE_SPIDER;
            case SILVERFISH:
                return org.bukkit.entity.EntityType.SILVERFISH;
            case BLAZE:
                return org.bukkit.entity.EntityType.BLAZE;
            case MAGMA_CUBE:
                return org.bukkit.entity.EntityType.MAGMA_CUBE;
            case ENDER_DRAGON:
                return org.bukkit.entity.EntityType.ENDER_DRAGON;
            case WITHER:
                return org.bukkit.entity.EntityType.WITHER;
            case BAT:
                return org.bukkit.entity.EntityType.BAT;
            case WITCH:
                return org.bukkit.entity.EntityType.WITCH;
            case ENDERMITE:
                return org.bukkit.entity.EntityType.ENDERMITE;
            case GUARDIAN:
                return org.bukkit.entity.EntityType.GUARDIAN;
            case SHULKER:
                return org.bukkit.entity.EntityType.SHULKER;
            case PIG:
                return org.bukkit.entity.EntityType.PIG;
            case SHEEP:
                return org.bukkit.entity.EntityType.SHEEP;
            case COW:
                return org.bukkit.entity.EntityType.COW;
            case CHICKEN:
                return org.bukkit.entity.EntityType.CHICKEN;
            case SQUID:
                return org.bukkit.entity.EntityType.SQUID;
            case WOLF:
                return org.bukkit.entity.EntityType.WOLF;
            case MOOSHROOM:
                return org.bukkit.entity.EntityType.MUSHROOM_COW;
            case SNOW_GOLEM:
                return org.bukkit.entity.EntityType.SNOWMAN;
            case OCELOT:
                return org.bukkit.entity.EntityType.OCELOT;
            case IRON_GOLEM:
                return org.bukkit.entity.EntityType.IRON_GOLEM;
            case HORSE:
                return org.bukkit.entity.EntityType.HORSE;
            case RABBIT:
                return org.bukkit.entity.EntityType.RABBIT;
            case POLAR_BEAR:
                return org.bukkit.entity.EntityType.POLAR_BEAR;
            case LLAMA:
                return org.bukkit.entity.EntityType.LLAMA;
            case LLAMA_SPIT:
                return org.bukkit.entity.EntityType.LLAMA_SPIT;
            case PARROT:
                return org.bukkit.entity.EntityType.PARROT;
            case VILLAGER:
                return org.bukkit.entity.EntityType.VILLAGER;
            case ENDER_CRYSTAL:
                return org.bukkit.entity.EntityType.ENDER_CRYSTAL;
            case PLAYER:
                return org.bukkit.entity.EntityType.PLAYER;
            default:
                throw new IllegalArgumentException("Unsupported entity type: " + type);
        }
    }
}
