package gg.warcraft.monolith.app;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import gg.warcraft.monolith.api.Library;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
